site_name: Shadox
site_url: https://shadox.github.io

theme:
  name: material
  language: ar
  direction: rtl

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: استخدام تفضيل النظام

    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-7
        name: تفعيل الوضع الداكن

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: purple
      toggle:
        icon: material/brightness-4
        name: تفعيل الوضع الفاتح

  features:
    - search.suggest
    - search.highlight
    - navigation.instant
    - content.code.copy

plugins:
  - search
  - literate-nav:
      nav_file: SUMMARY.md

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - toc:
      toc_depth: 3

extra_css:
  - stylesheets/extra.css
